export const categories = [
	{ id: 1, title: "Smart" },
	{ id: 2, title: "Digital" },
	{ id: 3, title: "Analogue" },
	{ id: 4, title: "Sport" },
	{ id: 5, title: "Chronograph" },
];

export const watchItems = [
	{
		id: 1,
		title: "Apple Watch Series 8",
		category: "Smart",
		brand: "Apple",
		description:
			"(GPS + Cellular, 45MM) - Silver Aluminum Case with M/L White Sport Band (Renewed Premium)",
		price: 329.0,
		image: require("../assets/image/series-8.png"),
		stars: "2.0",
	},
	{
		id: 2,
		title: "Apple Watch Series 8",
		category: "Smart",
		brand: "Apple",
		description:
			"[GPS + Cellular, 45mm] - Midnight Aluminum Case with Midnight Sport Band, M/L (Renewed)",
		price: 249.59,
		image: require("../assets/image/series-8-black.png"),
		stars: "4.3",
	},
	{
		id: 3,
		title: "Apple Watch Series 9",
		category: "Smart",
		brand: "Apple",
		description:
			"[GPS 41mm] Smartwatch with Pink Aluminum Case with Pink Sport Loop. Fitness Tracker, Blood Oxygen & ECG Apps, Always-On Retina Display, Carbon Neutral",
		price: 599.99,
		image: require("../assets/image/s9.png"),
		stars: "4.3",
	},
	{
		id: 4,
		title: "Apple Watch SE (2nd Gen)",
		category: "Smart",
		brand: "Apple",
		description:
			"[GPS + Cellular 44mm] Smartwatch with Silver Aluminum Case with Storm Blue Sport Band S/M. Fitness & Sleep Tracker, Crash...",
		price: 299.59,
		image: require("../assets/image/s9.png"),
		stars: "4.3",
	},
	{
		id: 5,
		title: " Eco-Drive",
		category: "Analogue",
		brand: "Citizen Watches",
		description: "Citizen Watches Men's CA0621-05L Eco-Drive",
		price: 159.29,
		image: require("../assets/image/eco-drive.png"),
		stars: "4.3",
	},
	{
		id: 6,
		title: " Pilot 41",
		category: "Analogue",
		brand: " Enclave Mfg Co.",
		description:
			"Enclave Pilot 41 Stainless Steel Quartz Chronograph Watches for Men with Analog Date",
		price: 399.59,
		image: require("../assets/image/pilot.png"),
		stars: "4.3",
	},
	{
		id: 7,
		title: "Rolex Submariner",
		category: "Analogue",
		brand: "Rolex",
		description:
			"Rolex Submariner Date Black Dial Yellow Gold/Steel Men's Watch 116613LN-0001",
		price: 669.59,
		image: require("../assets/image/rolex-watch.png"),
		stars: "4.1",
	},
	{
		id: 8,
		title: " Mr. Daddy 2.0 ",
		category: "Chronograph",
		brand: "Diesel",
		description:
			"Diesel Mr. Daddy 2.0 Men's Watch with Oversized Chronograph Watch Dial and Stainless Steel, Silicone or Leather Band",
		price: 499.59,
		image: require("../assets/image/mr_daddy-1.png"),
		stars: "4.3",
	},
	{
		id: 9,
		title: "Mr. Daddy 2.0 Men's",
		category: "Chronograph",
		brand: "Diesel",
		description:
			"Diesel Mr. Daddy 2.0 Men's Watch with Oversized Chronograph Watch Dial and Stainless Steel, Gold",
		price: 699.59,
		image: require("../assets/image/mr_daddy-2.png"),
		stars: "4.3",
	},
	{
		id: 10,
		title: " Mr. Daddy 2.0 ",
		category: "Chronograph",
		brand: "Diesel",
		description:
			"Diesel Mr. Daddy 2.0 Men's Watch with Oversized Chronograph Watch Dial and Stainless Steel, Silicone or Leather Band",
		price: 499.59,
		image: require("../assets/image/mr_daddy-2.png"),
		stars: "4.3",
	},
	{
		id: 11,
		title: "G-Shock GA-700UC",
		category: "Sport",
		brand: "G-Shock",
		description:
			"200 Meter Water Resistant, Super Illuminator LED Light with Afterglow",
		price: 399.59,
		image: require("../assets/image/g-shock.png"),
		stars: "4.3",
	},
	{
		id: 12,
		title: "Armitron Sport Men's",
		category: "Sport",
		brand: "Armitron",
		description:
			"Armitron Sport Men's Digital Chronograph Resin Strap Watch,Black resin case with textured top ring; lcd display with time, seconds, day and date; yellow resin strap with buckle closure",
		price: 399.59,
		image: require("../assets/image/armitron.png"),
		stars: "4.3",
	},
	{
		id: 13,
		title: "Armitron Sport Mens",
		category: "Smart",
		brand: "Armitron",
		description:
			"Armitron Sport Men's Digital Chronograph Resin Strap Watch,Military green resin case and textured top ring",
		price: 29.59,
		image: require("../assets/image/armitron-green.png"),
		stars: "4.3",
	},
	{
		id: 14,
		title: "Casio Men's A158WA-1DF ",
		category: "Digital",
		brand: "Apple",
		description:
			"Casio Men's A158WA-1DF Stainless Steel Digital Watch with Luminous rectangular dial with alarm and stopwatch",
		price: 21.59,
		image: require("../assets/image/casio-1.png"),
		stars: "4.3",
	},
	{
		id: 15,
		title: "SKMEI Gold Men's",
		category: "Digital",
		brand: "SKMEI ",
		description:
			"Digital Sports Watch Men's Women Water Resistant Outdoor Stainless Steel Band Electronic Square LED Back Light Wristwatch Gold",
		price: 399.59,
		image: require("../assets/image/dw.png"),
		stars: "4.3",
	},
	{
		id: 16,
		title: "Reginald LED ",
		category: "Digital",
		brand: "Reginald",
		description:
			"Reginald Watches for Men Fashion Trend Multifunction Outdoor Sports Watch LED Large Digital Display Chronograph Stainless Steel Square Watches",
		price: 399.59,
		image: require("../assets/image/reginald.png"),
		stars: "4.3",
	},
	{
		id: 17,
		title: "Daniel Wellington Petite Evergold Watch ",
		category: "Analogue",
		brand: "Daniel Wellington",
		description:
			"Daniel Wellington Petite Evergold Watch, Gold Mesh Bracelet.Refined Gold Double Plating On 316L Stainless Steel   28mmmm dial in Eggshell White Japanese Quartz Movement",
		price: 399.59,
		image: require("../assets/image/dw.png"),
		stars: "4.3",
	},
	{
		id: 18,
		title: "CRRJU Men's Watch ",
		category: "Analogue",
		brand: "CRRJU",
		description:
			"CRRJU Watches for Men Luxury Business Stainless Steel Waterproof Calendar Chronograph Analog Quartz Wristwatches",
		price: 399.59,
		image: require("../assets/image/CRRJU.png"),
		stars: "4.3",
	},
	{
		id: 19,
		title: "Endo Turbo v2 ",
		category: "Analogue",
		brand: "Caveman",
		description:
			"The EndoTurbo v2 allows a view into the mesmerizing complications.This watch feels alive on your wrists at all times.  An attention seeker.",
		price: 250.59,
		image: require("../assets/image/caveman.png"),
		stars: "4.3",
	},
	{
		id: 20,
		title: "Endo Turbo v2 ",
		category: "Chronograph",
		brand: "Caveman",
		description:
			"The EndoTurbo v2 allows a view into the mesmerizing complications.This watch feels alive on your wrists at all times.  An attention seeker.",
		price: 250.59,
		image: require("../assets/image/caveman.png"),
		stars: "4.3",
	},
	{
		id: 21,
		title: "Movado 3600944 Bold Verso Men's2 ",
		category: "Analogue",
		brand: "Mavado",
		description:
			"Movado 3600944 Bold Verso Men's Swiss Quartz Stainless Steel Case and Leather Strap Watch, Color: Cognac",
		price: 550.59,
		image: require("../assets/image/movado-1.png"),
		stars: "4.8",
	},
	{
		id: 22,
		title: "Movado Mens Evolution ",
		category: "Analogue",
		brand: "Mavado",
		description:
			"Movado Men's Bold Evolution Swiss Quartz Watch with Stainless Steel Link Bracelet, Blue",
		price: 650.59,
		image: require("../assets/image/movado-2.png"),
		stars: "4.1",
	},
	{
		id: 23,
		title: "Movado Women Stainless Steel ",
		category: "Analogue",
		brand: "Mavado",
		description:
			"Movado Bold Access Women's Stainless Steel Watch.Women's Movado Bold Access, stainless steel case and mesh bracelet, gold Museum dial with flat dot.",
		price: 399.99,
		image: require("../assets/image/movado-2.png"),
		stars: "4.0",
	},
	{
		id: 23,
		title: "Movado Women Stainless Steel ",
		category: "Analogue",
		brand: "Mavado",
		description:
			"Movado Bold Verso Women's Swiss Quartz 3600932 Ionic Plated Light Gold Steel Case and Link Bracelet Watch, Color: Black. he classic bracelet and statement-making 40mm case are crafted from bright white ceramic for a flawlessly refined finish. The matching white chronograph dial features three subdials, a date window with pale yellow gold toned details and Swiss Super-LumiNova accents",
		price: 685.49,
		image: require("../assets/image/movado-3.png"),
		stars: "3.7",
	},
	{
		id: 24,
		title: "Movado Women Stainless Steel ",
		category: "Chronograph",
		brand: "Mavado",
		description:
			"Movado 3600933 Bold Verso Women's Swiss Quartz Ionic Plated Light Gold Steel and Ceramic Link Bracelet Watch, Color: White.The classic bracelet and statement-making 40 mm case are crafted from bright white ceramic for a flawlessly refined finish. The matching white chronograph dial features three subdials, a date window with pale yellow gold toned details and Swiss Super-LumiNova accents.",
		price: 681.89,
		image: require("../assets/image/movado-4.png"),
		stars: "3.8",
	},
	{
		id: 25,
		title: "Movado Women Stainless Steel ",
		category: "Chronograph",
		brand: "Mavado",
		description:
			"Movado 3600933 Bold Verso Women's Swiss Quartz Ionic Plated Light Gold Steel and Ceramic Link Bracelet Watch, Color: White.The classic bracelet and statement-making 40 mm case are crafted from bright white ceramic for a flawlessly refined finish. The matching white chronograph dial features three subdials, a date window with pale yellow gold toned details and Swiss Super-LumiNova accents.",
		price: 681.89,
		image: require("../assets/image/movado-5.png"),
		stars: "4.6",
	},
	{
		id: 26,
		title: "Movado Bold Verso Women's  ",
		category: "Chronograph",
		brand: "Mavado",
		description:
			"Movado Bold Verso Women's Swiss Quartz 3600935 Blush Ceramic Case and Link Bracelet Watch, Color: Blush.This statement-making 39mm case is paired with an ultra-contemporary ceramic bracelet, all in monochromatic blush with gleaming pale rose gold ion-plated accents. The tonal dial features our iconic dot motif at 12:00, a date window, and Swiss Super-LumiNova accents.",
		price: 895.89,
		image: require("../assets/image/movado-6.png"),
		stars: "4.6",
	},
	{
		id: 27,
		title: " NW/1678WTWT",
		category: "Chronograph",
		brand: "Nine West",
		description:
			"Nine West Women's NW/1678WTWT Matte White Rubberized Bracelet Watch.42mm boyfriend size case; matte white dial with gold-tone hands and markers.Matte white rubberized adjustable link bracelet; fold over clasp with double push-button safety; inner circumference 6 3/4 inches			",
		price: 19.99,
		image: require("../assets/image/nine-west.png"),
		stars: "4.1",
	},
	{
		id: 28,
		title: " Bulova Classic Diamond",
		category: "Analogue",
		brand: "Nine West",
		description:
			"Bulova Ladies' Classic Diamond Two-Tone Stainless Steel 3-Hand Quartz Watch, Rectangle Silver Dial Style: 98P205		",
		price: 19.99,
		image: require("../assets/image/bulova.png"),
		stars: "4.1",
	},
	{
		id: 29,
		title: "Iaret Smart Watch for Women",
		category: "Smart",
		brand: "Laret",
		description:
			"Iaret Smart Watch for Women(Call Receive/Dial), Fitness Tracker Waterproof Smartwatch for Android iOS Phones 1.7 HD Full Touch Screen Digital Watches with Heart Rate Sleep Monitor Pedometer, Gold",
		price: 39.99,
		image: require("../assets/image/laret.png"),
		stars: "4.1",
	},
	{
		id: 30,
		title: "Iaret Smart Watch for Women",
		category: "Smart",
		brand: "Laret",
		description:
			"Iaret Smart Watch for Women (Answer/Make Call), Fitness Tracker for Android and iOS Phones Waterproof Smartwatch with 1.32 HD Full Touch Screen AI Voice Control Heart Rate Sleep Monitor Pedometer",
		price: 47.99,
		image: require("../assets/image/laret-2.png"),
		stars: "4.1",
	},
	{
		id: 31,
		title: "Military Smart Watch for Men",
		category: "Smart",
		brand: "Laret",
		description:
			"Military Smart Watch for Men(Answer/Dial Calls),100 Sports Modes, 5ATM Waterproof Fitness Watch with Heart Rate/SpO2/Blood Pressure for Android and iOS,1.39''HD DIY Screen Smartwatch Black",
		price: 47.99,
		image: require("../assets/image/military-smart.png"),
		stars: "4.1",
	},
	{
		id: 32,
		title: "AMAZTIM Smart Watch",
		category: "Smart",
		brand: "AMAZTIM",
		description:
			"AMAZTIM Smart Watch for Men,60days Extra-Long Battery Life(Call Receive/Dial), 50M Waterproof,Rugged Military Fitness Watch for iPhone Android,70 Sports,1.85 Heart Rate Sleep/Blood Pressure Watch",
		price: 79.99,
		image: require("../assets/image/AMAZTIM.png"),
		stars: "4.1",
	},
	{
		id: 33,
		title: "Samsung Galaxy 6 Smart Watch",
		category: "Sport",
		brand: "Samsung",
		description:
			"SAMSUNG Galaxy Watch 6 Bespoke Edition 44mm Exclusive Bluetooth Smartwatch, Health, Fitness, Sleep, HR Tracker, Improved Battery, Sapphire Crystal Glass, US Version Graphite Extreme Sport Band, Etoupe",
		price: 399.99,
		image: require("../assets/image/samsung.png"),
		stars: "4.8",
	},
	{
		id: 34,
		title: "Laverado Digital Watches",
		category: "Digital",
		brand: "Laverado",
		description:
			"Lavaredo Digital Sport Outdoor Multifunctional Chronograph LED 50 M Waterproof Alarm Calendar Analog Watch for Children with Silicone Band.",
		price: 16.99,
		image: require("../assets/image/laverado.png"),
		stars: "4.8",
	},
	{
		id: 35,
		title: "Laverado Digital Watches",
		category: "Digital",
		brand: "Armitron",
		description:
			"Armitron Sport Men's Digital Chronograph Resin Strap Watch, 40/8284",
		price: 16.99,
		image: require("../assets/image/armitron-2.png"),
		stars: "4.8",
	},
	{
		id: 36,
		title: "Armitron Digital Watches",
		category: "Digital",
		brand: "Armitron",
		description:
			"Armitron Sport Men's Digital Chronograph Resin Strap Watch, 40/8284",
		price: 16.99,
		image: require("../assets/image/armitron-3.png"),
		stars: "4.8",
	},
	{
		id: 37,
		title: "Gosasa Digital Watches",
		category: "Sport",
		brand: "Gosasa",
		description:
			"Gosasa Men's Watches Multi Function Military S-Shock Sports Watch LED Digital Waterproof Alarm Watches",
		price: 16.99,
		image: require("../assets/image/gosasa.png"),
		stars: "4.8",
	},
	{
		id: 38,
		title: "Palada Sport Watches",
		category: "Sport",
		brand: "palada",
		description:
			"PALADA Men's Digital Sports Watch Waterproof Tactical Watch with LED Backlight Watch for Men",
		price: 16.99,
		image: require("../assets/image/palada.png"),
		stars: "4.8",
	},
	{
		id: 39,
		title: "Palada Sport Watches",
		category: "Sport",
		brand: "palada",
		description:
			"PALADA Men's Digital Sports Watch Waterproof Tactical Watch with LED Backlight Watch for Men",
		price: 16.99,
		image: require("../assets/image/palada.png"),
		stars: "4.8",
	},
];
